interfaces:
  hundredGigE 1/1:
    fanout:
      type: "quad"
      speed: "25G"
  twentyFiveGigE 1/1/1:
    description: "U3-S1-P2"
    allowlist:
      - "description"
  twentyFiveGigE 1/1/2:
    description: "U3-S3-P2"
    allowlist:
      - "description"
  twentyFiveGigE 1/1/3:
    description: "U5-S1-P2"
    allowlist:
      - "description"
  twentyFiveGigE 1/1/4:
    description: "U5-S3-P2"
    allowlist:
      - "description"
  hundredGigE 1/2:
    fanout:
      type: "quad"
      speed: "25G"
  twentyFiveGigE 1/2/1:
    description: "U7-S1-P2"
    allowlist:
      - "description"
  twentyFiveGigE 1/2/2:
    description: "U7-S3-P2"
    allowlist:
      - "description"
  twentyFiveGigE 1/2/3:
    description: "U9-S1-P2"
    allowlist:
      - "description"
  twentyFiveGigE 1/2/4:
    description: "U9-S3-P2 OAC Prod Infra Compute 3 (Temp)"
    state: "up"
    mtu: 9216
    portmode: "access"
    untagged: 2311
    stp:
      edgeport: true
      bpduguard: true
  hundredGigE 1/3:
    fanout:
      type: "quad"
      speed: "25G"
  twentyFiveGigE 1/3/1:
    description: "U11-S1-P2"
    allowlist:
      - "description"
  twentyFiveGigE 1/3/2:
    description: "U11-S3-P2 OAC Prod Infra Compute 2 (Temp)"
    state: "up"
    mtu: 9216
    portmode: "access"
    untagged: 2311
    stp:
      edgeport: true
      bpduguard: true
  twentyFiveGigE 1/3/3:
    description: "U13-S1-P2"
    allowlist:
      - "description"
  twentyFiveGigE 1/3/4:
    description: "U13-S3-P2"
    allowlist:
      - "description"
  hundredGigE 1/4:
    fanout:
      type: "quad"
      speed: "25G"
  twentyFiveGigE 1/4/1:
    description: "U15-S1-P2"
    allowlist:
      - "description"
  twentyFiveGigE 1/4/2:
    description: "U15-S3-P2"
    allowlist:
      - "description"
  twentyFiveGigE 1/4/3:
    description: "U17-S1-P2"
    allowlist:
      - "description"
  twentyFiveGigE 1/4/4:
    description: "U17-S3-P2"
    allowlist:
      - "description"
  hundredGigE 1/5:
    fanout:
      type: "quad"
      speed: "25G"
  twentyFiveGigE 1/5/1:
    description: "U19-S1-P2 OAC Prod Infra Compute 1 (Temp)"
    state: "up"
    mtu: 9216
    portmode: "access"
    untagged: 2311
    stp:
      edgeport: true
      bpduguard: true
  twentyFiveGigE 1/5/2:
    description: "U19-S3-P2"
    allowlist:
      - "description"
  twentyFiveGigE 1/5/3:
    description: "U21-S1-P2"
    allowlist:
      - "description"
  twentyFiveGigE 1/5/4:
    description: "U21-S3-P2"
    allowlist:
      - "description"
  hundredGigE 1/6:
    fanout:
      type: "quad"
      speed: "25G"
  twentyFiveGigE 1/6/1:
    description: "U23-S1-P2"
    allowlist:
      - "description"
  twentyFiveGigE 1/6/2:
    description: "U23-S3-P2"
    allowlist:
      - "description"
  twentyFiveGigE 1/6/3:
    description: "U25-S1-P2 OAC Staging 1"
    state: "up"
    mtu: 9216
    portmode: "access"
    untagged: 2312
    stp:
      edgeport: true
      bpduguard: true
  twentyFiveGigE 1/6/4:
    description: "U25-S3-P2 OAC Prod 1"
    state: "up"
    mtu: 9216
    portmode: "access"
    untagged: 2313
    stp:
      edgeport: true
      bpduguard: true
  hundredGigE 1/7:
    fanout:
      type: "quad"
      speed: "25G"
  twentyFiveGigE 1/7/1:
    description: "U27-S1-P2 OAC Staging 2"
    state: "up"
    mtu: 9216
    portmode: "access"
    untagged: 2312
    stp:
      edgeport: true
      bpduguard: true
  twentyFiveGigE 1/7/2:
    description: "U27-S3-P2 OAC Prod 2"
    state: "up"
    mtu: 9216
    portmode: "access"
    untagged: 2313
    stp:
      edgeport: true
      bpduguard: true
  twentyFiveGigE 1/7/3:
    description: "U29-S1-P2 OAC Staging 3"
    state: "up"
    mtu: 9216
    portmode: "access"
    untagged: 2312
    stp:
      edgeport: true
      bpduguard: true
  twentyFiveGigE 1/7/4:
    description: "U29-S3-P2 OAC Prod 3"
    state: "up"
    mtu: 9216
    portmode: "access"
    untagged: 2313
    stp:
      edgeport: true
      bpduguard: true
  hundredGigE 1/8:
    state: "down"
  hundredGigE 1/9:
    state: "down"
  hundredGigE 1/10:
    state: "down"
  hundredGigE 1/11:
    state: "down"
  hundredGigE 1/12:
    state: "down"
  hundredGigE 1/13:
    state: "down"
  hundredGigE 1/14:
    state: "down"
  hundredGigE 1/15:
    state: "down"
  hundredGigE 1/16:
    state: "down"
  hundredGigE 1/17:
    fanout:
      type: "single"
      speed: "40G"
  fortyGigE 1/17/1:
    description: U29-S1 (NVME)
    allowlist:
      - "description"
  hundredGigE 1/18:
    state: "down"
  hundredGigE 1/19:
    state: "down"
  hundredGigE 1/20:
    state: "down"
  hundredGigE 1/21:
    fanout:
      type: "quad"
      speed: "10G"
  TenGigabitEthernet 1/21/1:
    description: "U31-S1A-P2"
    allowlist:
      - "description"
  TenGigabitEthernet 1/21/2:
    description: "U31-S1B-P2"
    allowlist:
      - "description"
  TenGigabitEthernet 1/21/3:
    description: "U31-S1C-P2"
    allowlist:
      - "description"
  TenGigabitEthernet 1/21/4:
    description: "U31-S1D-P2"
    allowlist:
      - "description"
  hundredGigE 1/22:
    fanout:
      type: "quad"
      speed: "10G"
  TenGigabitEthernet 1/22/1:
    description: "U31-S3A-P2"
    allowlist:
      - "description"
  TenGigabitEthernet 1/22/2:
    description: "U31-S3B-P2"
    allowlist:
      - "description"
  TenGigabitEthernet 1/22/3:
    description: "U31-S3C-P2"
    allowlist:
      - "description"
  TenGigabitEthernet 1/22/4:
    description: "U31-S3D-P2"
    allowlist:
      - "description"
  hundredGigE 1/23:
    fanout:
      type: "quad"
      speed: "10G"
  TenGigabitEthernet 1/23/1:
    description: "U33-S1A-P2 OAC Infra 1"
    state: "up"
    mtu: 9216
    portmode: "access"
    untagged: 2311
    stp:
      edgeport: true
      bpduguard: true
  TenGigabitEthernet 1/23/2:
    description: "U33-S1B-P2"
    allowlist:
      - "description"
  TenGigabitEthernet 1/23/3:
    description: "U33-S1C-P2 OAC Dev Workload1 1"
    state: "up"
    mtu: 9216
    portmode: "access"
    untagged: 2315
    tagged: 2317
    stp:
      edgeport: true
      bpduguard: true
  TenGigabitEthernet 1/23/4:
    description: "U33-S1D-P2"
    allowlist:
      - "description"
  hundredGigE 1/24:
    fanout:
      type: "quad"
      speed: "10G"
  TenGigabitEthernet 1/24/1:
    description: "U33-S3A-P2"
    allowlist:
      - "description"
  TenGigabitEthernet 1/24/2:
    description: "U33-S3B-P2 Dev Workload1 2"
    state: "up"
    mtu: 9216
    portmode: "access"
    untagged: 2315
    tagged: 2317
    stp:
      edgeport: true
  TenGigabitEthernet 1/24/3:
    description: "U33-S3C-P2"
    allowlist:
      - "description"
  TenGigabitEthernet 1/24/4:
    description: "U33-S3D-P2"
    allowlist:
      - "description"
  hundredGigE 1/25:
    fanout:
      type: "quad"
      speed: "10G"
  TenGigabitEthernet 1/25/1:
    description: "U35-S1A-P2"
    allowlist:
      - "description"
  TenGigabitEthernet 1/25/2:
    description: "U35-S1B-P2"
    allowlist:
      - "description"
  TenGigabitEthernet 1/25/3:
    description: "U35-S1C-P2"
    allowlist:
      - "description"
  TenGigabitEthernet 1/25/4:
    description: "U35-S1D-P2"
    allowlist:
      - "description"
  hundredGigE 1/26:
    fanout:
      type: "quad"
      speed: "10G"
  TenGigabitEthernet 1/26/1:
    description: "U35-S3A-P2"
    allowlist:
      - "description"
  TenGigabitEthernet 1/26/2:
    description: "U35-S3B-P2 OAC Infra 2"
    state: "up"
    mtu: 9216
    portmode: "access"
    untagged: 2311
    stp:
      edgeport: true
      bpduguard: true
  TenGigabitEthernet 1/26/3:
    description: "U35-S3C-P2"
    allowlist:
      - "description"
  TenGigabitEthernet 1/26/4:
    description: "U35-S3D-P2"
    allowlist:
      - "description"
  hundredGigE 1/27:
    fanout:
      type: "quad"
      speed: "10G"
  TenGigabitEthernet 1/27/1:
    description: "U37-S1A-P2 OAC Bastion"
    state: "up"
    mtu: 9216
    portmode: "access"
    untagged: 911
    stp:
      edgeport: true
      bpduguard: true
  TenGigabitEthernet 1/27/2:
    description: "U37-S1B-P2"
    allowlist:
      - "description"
  TenGigabitEthernet 1/27/3:
    description: "U37-S1C-P2"
    allowlist:
      - "description"
  TenGigabitEthernet 1/27/4:
    description: "U37-S1D-P2"
    allowlist:
      - "description"
  hundredGigE 1/28:
    fanout:
      type: "quad"
      speed: "10G"
  TenGigabitEthernet 1/28/1:
    description: "U37-S3A-P2"
    allowlist:
      - "description"
  TenGigabitEthernet 1/28/2:
    description: "U37-S3B-P2"
    allowlist:
      - "description"
  TenGigabitEthernet 1/28/3:
    description: "U37-S3C-P2 OAC Infra 3"
    state: "up"
    mtu: 9216
    portmode: "access"
    untagged: 2311
    stp:
      edgeport: true
      bpduguard: true
  TenGigabitEthernet 1/28/4:
    description: "U37-S3D-P2"
    allowlist:
      - "description"
  hundredGigE 1/29:
    state: "down"
  hundredGigE 1/30:
    description: "Uplink MOC-CORE-3 Port ####"
    state: "up"
    mtu: 9216
  hundredGigE 1/31:
    description: "VLT Link 1"
    state: "up"
  hundredGigE 1/32:
    description: "VLT Link 2"
    state: "up"
  TenGigabitEthernet 1/33:
    description: "MOC-R4PAC08-SW-MGMT Port 52"
    state: "up"
    mtu: 9216
  TenGigabitEthernet 1/34:
    state: "down"
  Port-channel 10:
    description: "MOC-CORE-3/4 Uplink"
    state: "up"
    mtu: 9216
    portmode: "trunk"
    tagged: "all"
    lacp-rate: "fast"
    lacp-members-active:
      - "hundredGigE 1/30"
    mlag: "Port-channel 10"
  Port-channel 100:
    description: "VLT Link"
    state: "up"
    mtu: 9216
    lag-members:
      - "hundredGigE 1/31"
      - "hundredGigE 1/32"
  Port-channel 101:
    description: "MOC-R4PAC10-SW-MGMT Uplink"
    state: "up"
    mtu: 9216
    portmode: "trunk"
    tagged: "all"
    lacp-rate: "fast"
    lacp-members-active:
      - "TenGigabitEthernet 1/33"
    mlag: "Port-channel 101"
  Vlan 911:
    state: "up"
    ip4: "10.2.13.2/19"
  Vlan 930:
    state: "up"
    ip4: "10.80.2.42/20"
